-- MySQL Script generated by MySQL Workbench
-- ven. 07 déc. 2018 19:48:04 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema m_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `m_db` ;

-- -----------------------------------------------------
-- Schema m_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `m_db` ;
USE `m_db` ;




-- -----------------------------------------------------
-- Table `m_db`.`user_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`user_question` (
  `question_id` INT(11) NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`question_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE UNIQUE INDEX `UK_UniqueQuestion` ON `m_db`.`user_question` (`question` ASC) ;

-- ----------------------------------------------------
-- Table `m_db`.`user_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`user_app` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(30) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `id_interne` INT(11) NULL DEFAULT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `nb_try` INT(11) NULL DEFAULT NULL,
  `password` VARCHAR(100) NOT NULL,
  `sso_id` VARCHAR(30) NOT NULL,
  `state` VARCHAR(30) NOT NULL,
  `user_question_question_id` INT(11)  ,
  PRIMARY KEY (`user_id`),
 CONSTRAINT `fk_user_app_user_question1`
    FOREIGN KEY (`user_question_question_id`)
    REFERENCES `m_db`.`user_question` (`question_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE UNIQUE INDEX `UK_SSO_ID` ON `m_db`.`user_app` (`sso_id` ASC) ;

CREATE INDEX `fk_user_app_user_question1_idx` ON `m_db`.`user_app` (`user_question_question_id` ASC) ;

 
-- -----------------------------------------------------
-- Table `m_db`.`user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`user_profile` (
  `user_profile_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`user_profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE UNIQUE INDEX `UK_TypeRoleUnique` ON `m_db`.`user_profile` (`type` ASC) ;


-- -----------------------------------------------------
-- Table `m_db`.`app_user_user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`app_user_user_profile` (
  `user_id` INT(11) NOT NULL,
  `user_profile_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `user_profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `IDX_USER_PROFIL_ID` ON `m_db`.`app_user_user_profile` (`user_profile_id` ASC) ;

ALTER TABLE app_user_user_profile
ADD CONSTRAINT FK_APP_USER FOREIGN KEY (user_id) REFERENCES user_app (user_id);

ALTER TABLE app_user_user_profile
ADD CONSTRAINT FK_USER_PROFILE FOREIGN KEY (user_profile_id) REFERENCES user_profile (user_profile_id);


-- -----------------------------------------------------
-- Table `m_db`.`banque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`banque` (
  `idbanque` INT NOT NULL AUTO_INCREMENT,
  `nom_banque` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(100) NULL,
  PRIMARY KEY (`idbanque`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `m_db`.`conseiller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`conseiller` (
  `idconseil` INT NOT NULL AUTO_INCREMENT,
  `nom_conseil` VARCHAR(30) NOT NULL,
  `prenom_conseil` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idconseil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

-- -----------------------------------------------------
-- Table `m_db`.`carte_bancaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`carte_bancaire` (
  `id_carte` INT NOT NULL AUTO_INCREMENT,
  `numcarte` VARCHAR(16) NOT NULL,
  `codecrypto` VARCHAR(3) NOT NULL,
  `echeance` DATETIME NOT NULL,
  `typecarte` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_carte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE UNIQUE INDEX `numcarte_UNIQUE` ON `m_db`.`carte_bancaire` (`numcarte` ASC) ;


-- -----------------------------------------------------
-- Table `m_db`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `numagency` VARCHAR(15) NOT NULL,
  `nom_client` VARCHAR(45) NOT NULL,
  `prenom_client` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NULL,
  `tel` VARCHAR(10) NULL,
  `tel_portable` VARCHAR(10) NULL,
  `typeClient` VARCHAR(10) NULL,
  `adresse` VARCHAR(150) NULL,
  `conseiller_idconseil` INT NOT NULL,
  `anneeArrive` DATE NOT NULL,
  PRIMARY KEY (`idclient`),
  CONSTRAINT `fk_client_conseiller1`
    FOREIGN KEY (`conseiller_idconseil`)
    REFERENCES `m_db`.`conseiller` (`idconseil`)
 )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE INDEX `fk_client_conseiller1_idx` ON `m_db`.`client` (`conseiller_idconseil` ASC) ;

-- -----------------------------------------------------
-- Table `m_db`.`banque_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`banque_client` (
  `banque_idbanque` INT NOT NULL,
  `client_idclient` INT NOT NULL,
  PRIMARY KEY (`banque_idbanque`, `client_idclient`),
  CONSTRAINT `fk_banque_has_client_banque1`
    FOREIGN KEY (`banque_idbanque`)
    REFERENCES `m_db`.`banque` (`idbanque`),
  CONSTRAINT `fk_banque_has_client_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `m_db`.`client` (`idclient`)
   )
ENGINE = InnoDB;

CREATE INDEX `fk_banque_client_client1_idx` ON `m_db`.`banque_client` (`client_idclient` ASC) ;

CREATE INDEX `fk_banque_has_client_banque1_idx` ON `m_db`.`banque_client` (`banque_idbanque` ASC) ;


-- -----------------------------------------------------
-- Table `m_db`.`alerte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`alerte` (
  `idalerte` INT NOT NULL AUTO_INCREMENT,
  `dateAlerte` DATE NOT NULL,
  `titre` VARCHAR(30) NOT NULL,
  `descriptif` VARCHAR(100) NULL,
  `typeEnvoi` VARCHAR(5) NOT NULL DEFAULT 'SMS',
  `client_idclient` INT NOT NULL,
  PRIMARY KEY (`idalerte`),
  CONSTRAINT `fk_alerte_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `m_db`.`client` (`idclient`)
   )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE INDEX `fk_alerte_client1_idx` ON `m_db`.`alerte` (`client_idclient` ASC) ;

-- -----------------------------------------------------
-- Table `m_db`.`infoCompte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`infoCompte` (
  `idinfoCompte` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  `montantPlafond` INT NOT NULL,
  `montantMinimum` INT NOT NULL,
  `tauxInteret` DECIMAL NOT NULL,
  PRIMARY KEY (`idinfoCompte`))
ENGINE = InnoDB DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `m_db`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`compte` (
  `idcompte` INT(11) NOT NULL AUTO_INCREMENT,
  `numecompte` INT(11) NOT NULL,
  `solde` DOUBLE NOT NULL,
  `typeCompte` VARCHAR(20) NOT NULL,
  `client_idclient` INT NOT NULL,
  `infoCompte_idinfoCompte` INT NULL,
  PRIMARY KEY (`idcompte`),
  CONSTRAINT `fk_compte_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `m_db`.`client` (`idclient`),
  CONSTRAINT `fk_compte_infoCompte1`
    FOREIGN KEY (`infoCompte_idinfoCompte`)
    REFERENCES `m_db`.`infoCompte` (`idinfoCompte`)
   )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE INDEX `fk_compte_client1_idx` ON `m_db`.`compte` (`client_idclient` ASC) ;

CREATE INDEX `fk_compte_infoCompte1_idx` ON `m_db`.`compte` (`infoCompte_idinfoCompte` ASC) ;


-- -----------------------------------------------------
-- Table `m_db`.`compteTiers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`compteTiers` (
  `idcompteTiers` INT NOT NULL,
  `codeActivation` VARCHAR(8) NULL,
  `Actif` TINYINT(1) NOT NULL,
  `dateCreation` DATETIME NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  `compte_idcompte` INT(11) NOT NULL,
  PRIMARY KEY (`idcompteTiers`),
  CONSTRAINT `fk_compteTiers_compte1`
    FOREIGN KEY (`compte_idcompte`)
    REFERENCES `m_db`.`compte` (`idcompte`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE INDEX `fk_compteTiers_compte1_idx` ON `m_db`.`compteTiers` (`compte_idcompte` ASC) ;




-- -----------------------------------------------------
-- Table `m_db`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`document` (
  `iddocument` INT NOT NULL AUTO_INCREMENT,
  `client_idclient` INT NOT NULL,
  `nom_doc` VARCHAR(45) NOT NULL,
  `emplacement` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iddocument`),
  CONSTRAINT `fk_document_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `m_db`.`client` (`idclient`))
ENGINE = InnoDB DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE INDEX `fk_document_client1_idx` ON `m_db`.`document` (`client_idclient` ASC) ;





-- -----------------------------------------------------
-- Table `m_db`.`operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`operation` (
  `idoperation` bigint NOT NULL AUTO_INCREMENT,
  `numOperation` INT NOT NULL,
  `dateOperation` DATETIME NOT NULL,
  `montant` DOUBLE NOT NULL,
  `typeOperation` VARCHAR(5) NOT NULL,
  `compte_idcompte` INT(11) NOT NULL,
  PRIMARY KEY (`idoperation`, `compte_idcompte`),
  CONSTRAINT `fk_operation_compte1`
    FOREIGN KEY (`compte_idcompte`)
    REFERENCES `m_db`.`compte` (`idcompte`))
ENGINE = InnoDB DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE INDEX `fk_operation_compte1_idx` ON `m_db`.`operation` (`compte_idcompte` ASC) ;




-- -----------------------------------------------------
-- Table `m_db`.`virement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`virement` (
  `idvirement` bigint NOT NULL AUTO_INCREMENT,
  `client_idclient` INT NOT NULL,
  `dateCreation` VARCHAR(45) NOT NULL,
  `typeVirement` VARCHAR(5) NOT NULL,
  `dateEcheance` VARCHAR(45) NOT NULL,
  `compte_Crediteur` INT(11) NOT NULL,
  `compte_Debiteur` INT(11) NOT NULL,
  PRIMARY KEY (`idvirement`),
  CONSTRAINT `fk_virement_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `m_db`.`client` (`idclient`),
  CONSTRAINT `fk_virement_compte1`
    FOREIGN KEY (`compte_Crediteur`)
    REFERENCES `m_db`.`compte` (`idcompte`),
  CONSTRAINT `fk_virement_compte2`
    FOREIGN KEY (`compte_Debiteur`)
    REFERENCES `m_db`.`compte` (`idcompte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1 AUTO_INCREMENT=1;

CREATE INDEX `fk_virement_client1_idx` ON `m_db`.`virement` (`client_idclient` ASC) ;

CREATE INDEX `fk_virement_compteCredit_idx` ON `m_db`.`virement` (`compte_Crediteur` ASC) ;

CREATE INDEX `fk_virement_compteDebit_idx` ON `m_db`.`virement` (`compte_Debiteur` ASC) ;

-- -----------------------------------------------------
-- Table `m_db`.`carte_bancaire_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_db`.`carte_bancaire_client` (
  `carte_idcarte` INT NOT NULL,
  `client_idclient` INT NOT NULL,
  PRIMARY KEY (`carte_idcarte`, `client_idclient`)
 )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;
alter table `m_db`.`carte_bancaire_client` add CONSTRAINT `fk_carte_bancaire_client_carte_bancaire1`
    FOREIGN KEY (`carte_idcarte`)
    REFERENCES `m_db`.`carte_bancaire` (`id_carte`);
alter table `m_db`.`carte_bancaire_client` add  CONSTRAINT `fk_carte_bancaire_client_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `m_db`.`client` (`idclient`);

CREATE INDEX `fk_carte_bancaire_client_client1_idx` ON `m_db`.`carte_bancaire_client` (`client_idclient` ASC) ;

CREATE INDEX `fk_carte_bancaire_client_carte_bancaire1_idx` ON `m_db`.`carte_bancaire_client` (`carte_idcarte` ASC) ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `m_db`.`user_app`
-- -----------------------------------------------------
START TRANSACTION;
USE `m_db`;
-- INSERT INTO `m_db`.`user_app` (`user_id`, `answer`, `email`, `first_name`, `id_interne`, `last_name`, `nb_try`, `password`, `sso_id`, `state`, `user_question_question_id`) VALUES (DEFAULT, '', 'linda49martin@gmail.com', 'linda', , 'Martin', , 'test', 'lmartin', 'Provisional', DEFAULT);

COMMIT;

