package fr.bicomat.entities;
// default package
// Generated 8 déc. 2018 07:10:38 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompteTiers generated by hbm2java
 */
@Entity
@Table(name = "compteTiers")
public class CompteTiers extends Compte implements java.io.Serializable {

	
	private String codeActivation;
	private boolean actif;
	private Date dateCreation;
	private String libelle;

	public CompteTiers() {
	}

	public CompteTiers( boolean actif, Date dateCreation, String libelle) {
	
		this.actif = actif;
		this.dateCreation = dateCreation;
		this.libelle = libelle;
	}

	/*public CompteTiers(int idcompteTiers, Compte compte, String codeActivation, boolean actif, Date dateCreation,
			String libelle) {
		this.i = idcompteTiers;
		this.compte = compte;
		this.codeActivation = codeActivation;
		this.actif = actif;
		this.dateCreation = dateCreation;
		this.libelle = libelle;
	}
*/
	


	@Column(name = "codeActivation", length = 8)
	public String getCodeActivation() {
		return this.codeActivation;
	}

	public void setCodeActivation(String codeActivation) {
		this.codeActivation = codeActivation;
	}

	@Column(name = "Actif", nullable = false)
	public boolean isActif() {
		return this.actif;
	}

	public void setActif(boolean actif) {
		this.actif = actif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCreation", nullable = false, length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "libelle", nullable = false, length = 45)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
