package fr.bicomat.entities;
// default package
// Generated 8 déc. 2018 07:10:38 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OperationId generated by hbm2java
 */
@Embeddable
public class OperationId implements java.io.Serializable {

	private long idoperation;
	private int compteIdcompte;

	public OperationId() {
	}

	public OperationId(long idoperation, int compteIdcompte) {
		this.idoperation = idoperation;
		this.compteIdcompte = compteIdcompte;
	}

	@Column(name = "idoperation", nullable = false)
	public long getIdoperation() {
		return this.idoperation;
	}

	public void setIdoperation(long idoperation) {
		this.idoperation = idoperation;
	}

	@Column(name = "compte_idcompte", nullable = false)
	public int getCompteIdcompte() {
		return this.compteIdcompte;
	}

	public void setCompteIdcompte(int compteIdcompte) {
		this.compteIdcompte = compteIdcompte;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OperationId))
			return false;
		OperationId castOther = (OperationId) other;

		return (this.getIdoperation() == castOther.getIdoperation())
				&& (this.getCompteIdcompte() == castOther.getCompteIdcompte());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdoperation();
		result = 37 * result + this.getCompteIdcompte();
		return result;
	}

}
