package fr.bicomat.entities;
// default package
// Generated 8 déc. 2018 07:10:38 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Operation generated by hbm2java
 */
@Entity
@Table(name = "operation")
public class Operation implements java.io.Serializable {

	private OperationId id;
	private Compte compte;
	private int numOperation;
	private Date dateOperation;
	private double montant;
	private String typeOperation;

	public Operation() {
	}

	public Operation(OperationId id, Compte compte, int numOperation, Date dateOperation, double montant,
			String typeOperation) {
		this.id = id;
		this.compte = compte;
		this.numOperation = numOperation;
		this.dateOperation = dateOperation;
		this.montant = montant;
		this.typeOperation = typeOperation;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idoperation", column = @Column(name = "idoperation", nullable = false)),
			@AttributeOverride(name = "compteIdcompte", column = @Column(name = "compte_idcompte", nullable = false)) })
	public OperationId getId() {
		return this.id;
	}

	public void setId(OperationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "compte_idcompte", nullable = false, insertable = false, updatable = false)
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	@Column(name = "numOperation", nullable = false)
	public int getNumOperation() {
		return this.numOperation;
	}

	public void setNumOperation(int numOperation) {
		this.numOperation = numOperation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateOperation", nullable = false, length = 19)
	public Date getDateOperation() {
		return this.dateOperation;
	}

	public void setDateOperation(Date dateOperation) {
		this.dateOperation = dateOperation;
	}

	@Column(name = "montant", nullable = false, precision = 22, scale = 0)
	public double getMontant() {
		return this.montant;
	}

	public void setMontant(double montant) {
		this.montant = montant;
	}

	@Column(name = "typeOperation", nullable = false, length = 5)
	public String getTypeOperation() {
		return this.typeOperation;
	}

	public void setTypeOperation(String typeOperation) {
		this.typeOperation = typeOperation;
	}

}
